pool:
  vmImage: 'Ubuntu 16.04'

variables:
  azureSubscription: 'Noel (7a458fa8-81c7-438f-a27e-2e11fdf4ecca)'
  resourceGroup: website
  location: westus2
  hugoVersion: 0.41
  baseName: noelbundick
  domainName: proxy.noelbundick.com

steps:

# Need to checkout submodules to pull the website theme
- checkout: self
  submodules: true

- task: Bash@3
  displayName: Build site using Hugo
  inputs:
    targetType: inline
    script: |
      # Install Hugo
      curl -Lo hugo.tar.gz "https://github.com/spf13/hugo/releases/download/v$(hugoVersion)/hugo_$(hugoVersion)_linux-64bit.tar.gz"
      tar xvf hugo.tar.gz
      ./hugo version
      # Build the site
      cd site
      $(Build.SourcesDirectory)/hugo -v

- task: AzureCLI@1
  displayName: Deploy Azure Resources
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: scriptPath
    scriptPath: azure/deploy-resources.sh
    arguments: '-g $(resourceGroup) -l $(location) -n $(baseName) -d $(domainName)'

- task: AzureCLI@1
  displayName: Deploy site content
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch --account-name $(baseName) -d '$web' -s ./site/public
