# All options: https://github.com/nodejh/hugo-theme-mini/blob/master/exampleSite/config.yaml

baseURL: /
languageCode: en-us
title: Noel Bundick
theme:
  - github.com/nodejh/hugo-theme-mini
paginate: 20
params:
  author: Noel Bundick
  customCSS:
    - css/custom.css
    - fontawesome/css/fontawesome.min.css
    - fontawesome/css/brands.min.css
  hiddenPostSummaryInHomePage: true
  relativeURLs: true
  showPowerBy: false
  showToc: true
social:
  github: https://www.github.com/noelbundick
  twitter: https://twitter.com/acanthamoeba
  linkedin: https://www.linkedin.com/in/noelbundick/
markup:
  highlight:
    guessSyntax: true
    style: solarized-dark
