# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Noel Bundick"
theme = "hugo-cactus-theme"
rssLink = "atom.xml"

paginate = 20

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-96602440-1"

# Disable comments by leaving disqusShortname empty
disqusShortname = "noelbundick"

[mediaTypes]
[mediaTypes."application/atom"]
  suffixes = ["xml"]

[outputFormats]
[outputFormats.RSS]
  mediaType = "application/atom"
  baseName = "atom"
  isPlainText = false

[author]
  name = "Noel Bundick"

[params]
	name = "Noel Bundick"
	description = ""
	bio = "Christian | Husband | Father | Software engineer"
	gravatar = "noelbundick@gmail.com"

	# Enter optionally your twitter account
	twitter = "acanthamoeba"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/zenburn.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "home"
	subscribe = "feed"

	# Pagination links
	olderPosts = "older"
	newerPosts = "newer"
	readMore = ""

	copyright = ""

	# Sharing options and author information in posts
	aboutAuthor = "Christian | Husband | Expectant father"
	tweet = "tweet"
	share = "share"

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    github   = "https://www.github.com/noelbundick"
    twitter  = "https://www.twitter.com/acanthamoeba"
    linkedin = "https://www.linkedin.com/in/noelbundick"

# Markdown engine configuration
[blackFriday]
		hrefTargetBlank = true