name: CI
on:
  push:
    branches:
    - master

env:
  githubUsername: noelbundick
  cloudflareEmail: noelbundick@gmail.com
  baseName: noelbundick

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Pull GitHub gists in as posts
      run: ./pull-gists.sh $githubUsername $githubPAT
      env:
        githubPAT: ${{ secrets.githubPAT }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.53'

    - name: Build site using Hugo
      run: |
        cd site
        hugo -v

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy site content
      uses: azure/CLI@v1
      with:
        inlineScript: az storage blob upload-batch --account-name $baseName -d '$web' -s ./site/public
